40Kollection/Controllers/CollectionsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Kollection.Model;
using Kollection.Model.Entities;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using Kollection.ViewModels;
using MoreLinq;

namespace Kollection.Controllers
{
    [OutputCache(NoStore = true, Duration = 0)]
    public class CollectionsController : Controller
    {
        private KollectionEntities db = new KollectionEntities();

        // GET: Collections
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            var collections = db.Collections.Include(c => c.User).Where(c => c.UserId == userId);
            
            ViewBag.MaxCollections = GetMaxCollections();
            return View(collections.ToList());
        }

        // GET: Collections/ShowAll
        public ActionResult ShowAll()
        {
            if (User.IsInRole("Admin"))
            {
                var collections = db.Collections.Include(c => c.User);

                ViewBag.MaxCollections = GetMaxCollections();
                return View(collections.ToList());
            }

            return new HttpStatusCodeResult(403);
        }

        // GET: Collections/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Collection collection = db.Collections.Find(id);
            if (collection == null)
            {
                return HttpNotFound();
            }

            CollectionDetailsViewModel vm = new CollectionDetailsViewModel()
            {
                Description = collection.Description,
                Id = collection.Id,
                Image = collection.Image,
                Name = collection.Name,
                UserId = collection.UserId,
                Units = new List<CollectionDetailsUnitViewModel>()
            };

            var units = db.Database.SqlQuery<CollectionDetailsUnitViewModel>(
                "select " +
                "un.Name, ( " +
                "    select distinct wg.Name as li " +
                "" +
                "    from Wargears wg " +
                "" +
                "    join CollectionUnitWargears cuw on cuw.WargearId = wg.Id " +
                "" +
                "    where cuw.CollectionUnitId = cu.Id " +
                "" +
                "    for xml path('') " +
                ") as Wargear " +
                "from " +
                "Units un " +
                "join CollectionUnits cu on cu.UnitId = un.Id " +
                "where " +
                $"cu.CollectionId = {id}"
            ).ToList();

            var distUnits = units.DistinctBy(x => x.Name+x.Wargear).ToList();
            
            foreach(var unit in distUnits)
            {
                //now get the quantity
                int count = units.Count(x => x.Name + x.Wargear == unit.Name + unit.Wargear);
                unit.Quantity = count;
                vm.Units.Add(unit);
            }

            return View(vm);
        }

        // GET: Collections/Create
        public ActionResult Create()
        {
            string userId = User.Identity.GetUserId();
            var collections = db.Collections.Include(c => c.User).Where(c => c.UserId == userId);
            if (collections.Count() < this.GetMaxCollections())
            {
                ViewBag.Units = db.Units.OrderBy(s => s.Name).ToList();
                return View();
            } 
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Collections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,Name,Description,Image")] Collection collection)
        {
            if (ModelState.IsValid)
            {
                db.Collections.Add(collection);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Units = db.Units.OrderBy(s => s.Name).ToList();
            return View(collection);
        }

        // GET: Collections/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Collection collection = db.Collections.Find(id);
            if (collection == null)
            {
                return HttpNotFound();
            }

            //We can assume this because the "find" from earlier was a success.
            collection = db.Collections.Include(c => c.Units).First(c => c.Id == id);

            //These are for the drop-down list
            ViewBag.Units = db.Units.OrderBy(s => s.Name).ToList();
            return View(collection);
        }

        // POST: Collections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,Name,Description,Image")] Collection collection)
        {
            if (ModelState.IsValid)
            {
                db.Entry(collection).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //These are for the drop-down list
            ViewBag.Units = db.Units.OrderBy(s => s.Name).ToList();
            return View(collection);
        }

        // GET: Collections/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Collection collection = db.Collections.Find(id);
            if (collection == null)
            {
                return HttpNotFound();
            }
            return View(collection);
        }

        // POST: Collections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Collection collection = db.Collections.Find(id);
            db.Collections.Remove(collection);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddUnits(int collectionId, int unitId, int[] wargearIds, int quantity)
        {
            for (int i = 0; i < quantity; i++)
            {
                CollectionUnit collUnit = new CollectionUnit() { CollectionId = collectionId, UnitId = unitId, Wargears = new List<CollectionUnitWargear>() };
                foreach (int wg in wargearIds) {
                    //Get the wargear itself
                    Wargear gear = db.Wargears.FirstOrDefault(g => g.Id == wg);
                    collUnit.Wargears.Add(new CollectionUnitWargear() { Wargear = gear });
                }
                db.CollectionUnits.Add(collUnit);
                db.SaveChanges();
            }

            var result = new { success = true };
            return Json(result);
        }

        private int GetMaxCollections()
        {
            if (User.IsInRole("Admin"))
            {
                return 999;
            }
            else
            {
                if (User.IsInRole("Subscriber"))
                {
                    return 10;
                }
                else
                {
                    return 1;
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

40Kollection/Controllers/Squads/SquadsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Kollection.Model;
using Kollection.Model.Entities;
using Microsoft.AspNet.Identity;
using Kollection.ViewModels;

namespace Kollection.Controllers.Squads
{
    [OutputCache(NoStore = true, Duration = 0)]
    public class SquadsController : Controller
    {
        private KollectionEntities db = new KollectionEntities();

        // GET: Squads
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            var squads = db.Squads.Include(s => s.SquadRole).Include(c => c.User).Where(c => c.UserId == userId);
            
            return View(squads.OrderBy(s => s.Name).ToList());
        }

        // GET: Squads/ShowAll
        public ActionResult ShowAll()
        {
            if (User.IsInRole("Admin"))
            {
                var squads = db.Squads.Include(s => s.SquadRole).Include(c => c.User);
                return View(squads.OrderBy(s => s.Name).ToList());
            }
            
            return new HttpStatusCodeResult(403);
        }

        // GET: Squads/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Squad squad = db.Squads.Find(id);
            if (squad == null)
            {
                return HttpNotFound();
            }
            return View(squad);
        }

        // GET: Squads/Create
        public ActionResult Create()
        {
            string userId = User.Identity.GetUserId();
            ViewBag.SquadRoleId = new SelectList(db.SquadRoles.OrderBy(r => r.Name), "Id", "Name");
            ViewBag.CollectionId = new SelectList(db.Collections.Where(c => c.UserId == userId).OrderBy(c => c.Name), "Id", "Name");
            ViewBag.Units = db.Units.OrderBy(u => u.Name);
            return View();
        }

        // POST: Squads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,UserId,Description,Image,SquadRoleId,CollectionId")] Squad squad)
        {
            if (ModelState.IsValid)
            {
                db.Squads.Add(squad);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            string userId = User.Identity.GetUserId();
            ViewBag.SquadRoleId = new SelectList(db.SquadRoles.OrderBy(r => r.Name), "Id", "Name");
            ViewBag.CollectionId = new SelectList(db.Collections.Where(c => c.UserId == userId).OrderBy(c => c.Name), "Id", "Name");
            ViewBag.Units = db.Units.OrderBy(u => u.Name);
            return View(squad);
        }

        // GET: Squads/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Squad squad = db.Squads.Find(id);
            if (squad == null)
            {
                return HttpNotFound();
            }

            string userId = User.Identity.GetUserId();
            ViewBag.SquadRoleId = new SelectList(db.SquadRoles.OrderBy(r => r.Name), "Id", "Name", squad.SquadRoleId);
            ViewBag.CollectionId = new SelectList(db.Collections.Where(c => c.UserId == userId).OrderBy(c => c.Name), "Id", "Name", squad.CollectionId);
            ViewBag.Units = db.Units.OrderBy(u => u.Name);

            SquadViewModel vm = new SquadViewModel()
            {
                Name = squad.Name,
                CollectionId = squad.CollectionId,
                Description = squad.Description,
                Id = squad.Id,
                Image = squad.Image,
                Points = squad.Points,
                SquadRoleId = squad.SquadRoleId,
                UserId = squad.UserId
            };

            var units = db.Database.SqlQuery<UnitWargearViewModel>(
                "select " +
                "un.Name as UnitName, cu.Id as CollectionUnitId, ( " +
                "    select distinct wg.Name as li " +
                "" +
                "    from Wargears wg " +
                "" +
                "    join CollectionUnitWargears cuw on cuw.WargearId = wg.Id " +
                "" +
                "    where cuw.CollectionUnitId = cu.Id " +
                "" +
                "    for xml path('') " +
                ") as UnitWargear " +
                "from " +
                "Units un " +
                "join CollectionUnits cu on cu.UnitId = un.Id " +
                "join SquadUnits su on su.CollectionUnitId = cu.Id " +
                "where " +
                $"su.SquadId = {id} "
            ).ToList();

            vm.Units = units;

            return View(vm);
        }

        // POST: Squads/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Image,SquadRoleId,CollectionId,UserId")] Squad squad)
        {
            if (ModelState.IsValid)
            {
                db.Entry(squad).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            string userId = User.Identity.GetUserId();
            ViewBag.SquadRoleId = new SelectList(db.SquadRoles.OrderBy(r => r.Name), "Id", "Name", squad.SquadRoleId);
            ViewBag.CollectionId = new SelectList(db.Collections.Where(c => c.UserId == userId).OrderBy(c => c.Name), "Id", "Name", squad.CollectionId);
            ViewBag.Units = db.Units.OrderBy(u => u.Name);

            SquadViewModel vm = new SquadViewModel()
            {
                Name = squad.Name,
                CollectionId = squad.CollectionId,
                Description = squad.Description,
                Id = squad.Id,
                Image = squad.Image,
                Points = squad.Points,
                SquadRoleId = squad.SquadRoleId,
                UserId = squad.UserId
            };

            return View(vm);
        }

        [HttpPost]
        public ActionResult AddUnits(int id, int[] collectionUnits)
        {
            foreach(int unit in collectionUnits)
            {
                db.SquadUnits.Add(new SquadUnit()
                {
                    SquadId = id,
                    CollectionUnitId = unit
                });
            }
            db.SaveChanges();
            int _points = 0;

            var squadUnits = db.SquadUnits.Where(su => su.SquadId == id).ToList();
            foreach(var squadUnit in squadUnits)
            {
                _points += squadUnit.UnitConfiguration.Unit.Points;

                foreach(var wargear in squadUnit.UnitConfiguration.Wargears)
                {
                    _points += wargear.Wargear.Points;
                }
            }

            var result = new { success = true, points = _points };
            return Json(result);
        }
        
        public ActionResult RemoveUnit(int id)
        {
            db.SquadUnits.RemoveRange(db.SquadUnits.Where(s => s.CollectionUnitId == id));
            db.SaveChanges();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        // GET: Squads/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Squad squad = db.Squads.Find(id);
            if (squad == null)
            {
                return HttpNotFound();
            }
            return View(squad);
        }

        // POST: Squads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.SquadUnits.RemoveRange(db.SquadUnits.Where(s => s.SquadId == id).ToList());
            db.SaveChanges();

            Squad squad = db.Squads.Find(id);
            db.Squads.Remove(squad);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

40Kollection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 40Kollection</title>
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700|Merriweather:400,700" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("40Kollection", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if ((int)ViewBag.UserLevel > 0)
                    {
                        switch ((int)ViewBag.UserLevel)
                        {
                            case 1:
                            @*If user is freebie, they only get one*@
                            <li>@Html.ActionLink("My Collection", "Index", "Collections")</li>
                                break;

                            case 2:
                                <li>@Html.ActionLink("My Collections", "Index", "Collections")</li>
                                break;

                            case 3:
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Collections <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("My Collections", "Index", "Collections")</li>
                                    <li>@Html.ActionLink("All Collections", "ShowAll", "Collections")</li>
                                </ul>
                            </li>
                            break;
                        }
                    }
                    @if ((int)ViewBag.UserLevel > 2) { 
                        @*Only Admin can add units, unit types, unit roles, etc.*@
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Units <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Units", "Index", "Units")</li>
                                <li>@Html.ActionLink("Unit Types", "Index", "UnitTypes")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Wargear <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Wargear", "Index", "Wargears")</li>
                                <li>@Html.ActionLink("Wargear Slots", "Index", "WargearSlots")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Squads <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("My Squads", "Index", "Squads")</li>
                                <li>@Html.ActionLink("All Squads", "ShowAll", "Squads")</li>
                                <li>@Html.ActionLink("Squad Roles", "Index", "SquadRoles")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

            
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; @DateTime.Now.Year - 40Kollection</p>
                </div>
                <div class="col-md-6 text-right">
                    <p>Another <a href="http://lucas-williams.com">Lucas Williams</a> project.</p>
                </div>
            </div>
        </div>
    </footer>
    
    <div class="modal fade" tabindex="-1" role="dialog" id="pageModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="~/Scripts/site.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>